### PR TITLE
Add a Refund method.

### PR DESCRIPTION
**Pull request by Archanium**
It supports partially refunding if an amount is set, otherwise it's a
full refund

### CODE REVIEW

**Comment by delatbabel** [comment]
Can you fix the errors noted in the travis build please?

**Comment by Archanium** [comment]
Fixed. :)

**Comment by PENDOnl** [comment]
Any idea when this PR is merged? Very useful method!

**Comment by delatbabel** [comment]
Merged, thanks.  Can you please confirm that this works in production and if so then I will tag for release.

**Comment by PENDOnl** [comment]
Will do today.

**Comment by PENDOnl** [comment]
Tried it in the test environment, and it works as expected:

```
// Payment was 2.50 EUR

$payment = \Omnipay::fetchTransaction(['transactionReference' => 'tr_JNtQgFxGbj'])->send();
$data = $payment->getData();
// $data['status'] = 'paid';

$refund = \Omnipay::refund(['transactionReference' => 'tr_JNtQgFxGbj'])->send();
$data = $refund->getData();
// $data['amountRefunded'] = "2.50"
// $data['status'] = 'refunded';
```

$data contains all payment details, including the new status and the full amount was refunded. Then I tried a partial refund:

```
// Payment was 1.50 EUR

$payment = \Omnipay::fetchTransaction(['transactionReference' => 'tr_k5JVdT29pU'])->send();
$data = $payment->getData();
// $data['status'] = 'paid';

$refund = \Omnipay::refund(['transactionReference' => 'tr_k5JVdT29pU', 'amount' => 1.00])->send();
$data = $refund->getData();
// $refund['amountRefunded'] = "1.00"
// $data['status'] = 'refunded';
```

So, also partial refunds seem to be working just fine! The response by Mollie however is significant different after a refund compared to before. But that is out of the scope of this merge. As far as I'm concerned this works perfect.

**Comment by PENDOnl** [comment]
Just one single thing I noticed, but I've got no clue if this has anything to do with this merge. But with the ~3.0 versie I was able to use ['id' => 'tr_a8j3k2'] as parameters with a request. But since using dev-master I have to rename id to transactionReference.

**Comment by Archanium** [comment]
PENDOnl, I have no idea why that should have changed, or rather, ever worked. :) Can you see which sha1 you have in your composer.lock?

But I don't think it's related to this, unless it is in one of the files I've changed.

**Comment by delatbabel** [comment]
> since using dev-master I have to rename id to transactionReference

It should always have been transactionReference. I have no idea why id ever worked.

**Comment by delatbabel** [comment]
Tagged. If one of you kind folks can please pick up and either correct or resubmit #23 then we can close that out too.

**Comment by PENDOnl** [comment]
Just to clear up what I mentioned: 

I noticed what happened, my $params are ['id' => 'tr_asS3ks'], but when creating a completePurchaseRequest the getData() method of the request looks for 'id' in the POST-request. Thus this works by default because Mollie sends the transactionReference as id-key in the POST-request. However it still feels strange and inconsistent, but at least it's not related to this PR.

**Pull request merged**
