### PR TITLE
[5.0] Support for Mandates API and Recurring payments.

### PR DESCRIPTION
**Pull request by jarnovanleeuwen**
Basically I took https://github.com/thephpleague/omnipay-mollie/pull/40 and updated the code to work with the Mollie v2 API. Also updated the tests and fixed some bugs.

Regards,
Jarno

### CODE REVIEW

**Comment by willemstuursma** [comment]
Hi @jarnovanleeuwen. Willem from Mollie here. Anything we can do to help this get landed?

**Comment by jarnovanleeuwen** [comment]
The PR should be ready :) Would be nice if someone could review this and release it.

**Comment by Jeroen-G** [comment]
What do you suggest is the best way to do mandates/recurring payments while this PR waits to get merged?

**Comment by jarnovanleeuwen** [comment]
I am using my own fork. In `composer.json`:

```json
"repositories": [
    {
        "type": "git",
        "url": "git@github.com:jarnovanleeuwen/omnipay-mollie.git"
    }
],
"require": {
    "omnipay/mollie": "dev-master"
}
```

@barryvdh Any chance on merging this? :-)

**Comment by barryvdh** [comment]
I've merged this, please test this using `^5.1@dev` (I bumped the minor version in the branch-alias to 5.1.x)

**Pull request merged**
