### PR TITLE
Add support for customer mandates

### PR DESCRIPTION
**Pull request by bouke-nederstigt**
This pull requests implements the create mandate, fetch mandate, and fetch customer mandates from Mollie. After adding a customer mandate it becomes possible to charge users using direct debit.  

Comments are welcome of course!

### CODE REVIEW

**Comment by Coennie** [comment]
+1 for this PR, please merge ASAP

**Comment by delatbabel** [comment]
The build is failing because the files submitted don't have correct termination.  Please ensure that all files end with a new line.

I can merge after that is fixed.

**Comment by bouke-nederstigt** [comment]
Fixed all the styling issues, as well as failing php 5.4 build. 
5.3 is still failing, but I don't know why. Is this a problem?

**Comment by sanderdekroon** [comment]
Please see this issue at TravisCI: https://github.com/travis-ci/travis-ci/issues/8219

Basically, TravisCI does not support PHP 5.3 on Trusty (Ubuntu 14.04). Trusty is the default Ubuntu release in Travis CI.

If you'd change the travis.yml to add `dist: precise`, you might be able to run PHP 5.3. Take a look at this link for more information: https://docs.travis-ci.com/user/reference/trusty/#PHP-images

I would recommend to merge this PR as soon as possible, as this is a create addition to the payment gateway.

**Comment by judgej** [comment]
The fact that Travis does not make php 5.3 support default is telling us something. Personally,  I would take it out of the list of versions tested. Even 5.5 is now giving us dependency problems. I try to use 5.6 minimum these days, with 5.5 as a nice-to-have if it doesn't involve extra effort.

**Comment by sanderdekroon** [comment]
While I do agree with you, Omnipay itself does support PHP 5.3. If this package would not, it would be quite inconsistent in my opinion.

**Comment by judgej** [comment]
It all comes down to how you want to support the users of this particular gateway driver. So long as composer.json declares its dependancies, then composer will handle the rest. The Mollie driver can be branched to support further PHP 5.3 releases if there is support for it. Anyway, that's just my view. I understand there are many users on many systems restricted by many factors. Everyone can be get what they need with the effort put into legacy branches.

Omnipay Common v2.5.2 supports PHP 5.3 to 7.1. Future versions of Omnipay Common will be PHP 5.6 minimum.

**Comment by Coennie** [comment]
@bouke-nederstigt thanks for all your work!

**Comment by jarnovanleeuwen** [comment]
Are there any plans on merging this?

**Comment by barryvdh** [comment]
Merged #56

**Comment by barryvdh** [comment]
Thanks for your work!

**Pull request closed without merging**
