### PR TITLE
#13 redirect failing due to not implementing Abstract Response

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by frederikbosch** [comment]
@eileenmcnaughton Please remove your last commit to another pull request. Then this PR is a fix for issue #13. But I find it very relevant that your easy fix gets merged ASAP.

**Comment by eileenmcnaughton** [comment]
OK - done

**Comment by frederikbosch** [comment]
@kayladnls Could you merge this PR? You now need to write the code below.

```php
if ($response->isRedirect()) {
    if ($response->getRedirectMethod() === 'GET') {
        $redirectUrl = $response->getRedirectUrl();
        $httpResponse->redirect($redirectUrl); // redirect using a framework/library for http response
    } else {
        $response->redirect();
    }
} else {
    // do something different
}
```

Whereas, the following code is what you would get after merging.

```php
if ($response->isRedirect()) {
    $response->redirect();
} else {
    // do something different
}
```

**Comment by naneri** [comment]
When will the PR be merged? I lot of people are waiting to integrate this to their projects :)

**Comment by frederikbosch** [comment]
Thank you @kayladnls :) Much appreciated. A new tag would be wonderful!

**Comment by dirkluijk** [comment]
:+1:  for new release (tag).

**Pull request merged**
